<a href="https://colab.research.google.com/github/ParvathamNithin/ML_23ag1a66g8/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np


In [6]:
array1=np.array([1,2])
print(array1)

[1 2]


In [7]:
array1=np.array([[1,2,3],[4,5,6]])
print(array1)


[[1 2 3]
 [4 5 6]]


In [23]:
  array2= np.array([[1, 2, 3], [4, 5, 6]])
  print(array2)

[[1 2 3]
 [4 5 6]]


In [26]:
 array3 = np.array([[[1, 2,1], [3, 4,3],[7,8,9]], [[5, 6,6], [7, 8,7],[1,0,3]]])
 print(array3)

[[[1 2 1]
  [3 4 3]
  [7 8 9]]

 [[5 6 6]
  [7 8 7]
  [1 0 3]]]


In [27]:
Data = np.array([10,20,30,40,50])
mean = np.mean(Data)
print(f"Mean is {mean}")
median = np.median(Data)
print(f"Meadian is {median}")


Mean is 30.0
Meadian is 30.0
